OPTIONAL { 
  ?item crm:P1_is_identified_by ?given_name_node. 
  ?given_name_node crm:P2_has_type <https://veniss.net/resource/type/given_name>;
    rdfs:label ?given_name_label. 
    BIND(CONCAT(", ", ?given_name_label, " ") AS ?given_name) 
} 

OPTIONAL { 
  ?item crm:P1_is_identified_by ?family_name_node. 
  ?family_name_node crm:P2_has_type <https://veniss.net/resource/type/family_name>;   
    rdfs:label ?family_name_label. 
  BIND(?family_name_label AS ?family_name) 
} 

OPTIONAL { 
  ?item crm:P1_is_identified_by ?alias_node. 
  ?alias_node crm:P2_has_type <https://veniss.net/resource/type/person_alias>;   
    rdfs:label ?alias_label. 
  BIND(CONCAT(" (", ?alias_label, ") ") AS ?alias) 
}
        
OPTIONAL { 
  ?item crm:P1_is_identified_by ?patronymic_node. 
  ?patronymic_node crm:P2_has_type <https://veniss.net/resource/type/person_patronymic>;   
    rdfs:label ?patronymic_label. 
  BIND(CONCAT("di ", ?patronymic_label) AS ?patronymic) 
}

BIND(COALESCE(?given_name, "") AS ?given_name_final) 
BIND(COALESCE(?family_name, "") AS ?family_name_final) 
BIND(COALESCE(?alias, "") AS ?alias_final) 
BIND(COALESCE(?patronymic, "") AS ?patronymic_final) 

BIND(CONCAT(?family_name_final, ?given_name_final, ?patronymic_final, ?alias_final) AS ?label)