name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title matches versioning format
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: PR title must be in the format vX.Y.Z"
            exit 1
          fi